src/Web/Grand.Web.Admin/Models/Permissions/PermissionActionModel.cs
using Grand.Infrastructure.Models;
using System.Collections.Generic;

namespace Grand.Web.Admin.Models.Permissions
{
    public partial class PermissionActionModel : BaseModel
    {
        public PermissionActionModel()
        {
            AvailableActions = new List<string>();
            DeniedActions = new List<string>();
        }
        public string SystemName { get; set; }
        public string PermissionName { get; set; }
        public string CustomerGroupId { get; set; }
        public string CustomerGroupName { get; set; }
        public IList<string> AvailableActions { get; set; }
        public IList<string> DeniedActions { get; set; }
    }
}

src/Web/Grand.Web.Admin/Models/Permissions/PermissionMappingModel.cs
using Grand.Infrastructure.Models;
using Grand.Web.Common.Models;
using System.Collections.Generic;

namespace Grand.Web.Admin.Models.Permissions
{
    public partial class PermissionMappingModel : BaseModel
    {
        public PermissionMappingModel()
        {
            AvailablePermissions = new List<PermissionRecordModel>();
            AvailableCustomerGroups = new List<CustomerGroupModel>();
            Allowed = new Dictionary<string, IDictionary<string, bool>>();
        }
        public IList<PermissionRecordModel> AvailablePermissions { get; set; }
        public IList<CustomerGroupModel> AvailableCustomerGroups { get; set; }

        //[permission system name] / [customer group id] / [allowed]
        public IDictionary<string, IDictionary<string, bool>> Allowed { get; set; }
    }
}

src/Web/Grand.Web.Admin/Models/Permissions/PermissionRecordModel.cs
using Grand.Infrastructure.Models;

namespace Grand.Web.Admin.Models.Permissions
{
    public partial class PermissionRecordModel : BaseModel
    {
        public string Name { get; set; }
        public string SystemName { get; set; }
        public string Area { get; set; }
        public bool Actions { get; set; }
        public string Category { get; set; }
    }
}

src/Web/Grand.Web.Admin/Controllers/PermissionController.cs
using Grand.Business.Common.Extensions;
using Grand.Business.Common.Interfaces.Directory;
using Grand.Business.Common.Interfaces.Localization;
using Grand.Business.Common.Interfaces.Logging;
using Grand.Business.Common.Interfaces.Security;
using Grand.Business.Common.Services.Security;
using Grand.Business.System.Commands.Models.Security;
using Grand.Web.Common.Filters;
using Grand.Web.Common.Models;
using Grand.Web.Common.Security.Authorization;
using Grand.Domain.Permissions;
using Grand.Infrastructure;
using Grand.Web.Admin.Models.Permissions;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Grand.Web.Admin.Controllers
{
    [PermissionAuthorize(PermissionSystemName.Acl)]
    public partial class PermissionController : BaseAdminController
    {
        #region Fields

        private readonly ILogger _logger;
        private readonly IWorkContext _workContext;
        private readonly IPermissionService _permissionService;
        private readonly IGroupService _groupService;
        private readonly ITranslationService _translationService;
        private readonly IMediator _mediator;

        #endregion

        #region Constructors

        public PermissionController(
            ILogger logger,
            IWorkContext workContext,
            IPermissionService permissionService,
            IGroupService groupService,
            ITranslationService translationService,
            IMediator mediator)
        {
            _logger = logger;
            _workContext = workContext;
            _permissionService = permissionService;
            _groupService = groupService;
            _translationService = translationService;
            _mediator = mediator;
        }

        #endregion

        #region Methods

        public async Task<IActionResult> Index()
        {
            var model = new PermissionMappingModel();

            var permissionRecords = await _permissionService.GetAllPermissions();
            var customerGroups = await _groupService.GetAllCustomerGroups(showHidden: true);
            foreach (var pr in permissionRecords.OrderBy(x=>x.Category))
            {
                model.AvailablePermissions.Add(new PermissionRecordModel
                {
                    Name = pr.GetTranslationPermissionName(_translationService, _workContext),
                    SystemName = pr.SystemName,
                    Area = pr.Area,
                    Category = pr.Category,
                    Actions = pr.Actions.Any()
                });
            }
            foreach (var cr in customerGroups)
            {
                model.AvailableCustomerGroups.Add(new CustomerGroupModel() { Id = cr.Id, Name = cr.Name });
            }
            foreach (var pr in permissionRecords)
                foreach (var cr in customerGroups)
                {
                    bool allowed = pr.CustomerGroups.Count(x => x == cr.Id) > 0;
                    if (!model.Allowed.ContainsKey(pr.SystemName))
                        model.Allowed[pr.SystemName] = new Dictionary<string, bool>();
                    model.Allowed[pr.SystemName][cr.Id] = allowed;
                }

            return View(model);
        }

        [HttpPost, ActionName("Index"), ArgumentNameFilter(KeyName = "save-continue", Argument = "install")]
        public async Task<IActionResult> PermissionsSave(IFormCollection form, bool install)
        {
            if (!install)
            {
                var permissionRecords = await _permissionService.GetAllPermissions();
                var customerGroups = await _groupService.GetAllCustomerGroups(showHidden: true);

                foreach (var cr in customerGroups)
                {
                    string formKey = "allow_" + cr.Id;
                    var permissionRecordSystemNamesToRestrict = form[formKey].ToString() != null ? form[formKey].ToString().Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries).ToList() : new List<string>();
                    foreach (var pr in permissionRecords)
                    {

                        bool allow = permissionRecordSystemNamesToRestrict.Contains(pr.SystemName);
                        if (allow)
                        {

                            if (pr.CustomerGroups.FirstOrDefault(x => x == cr.Id) == null)
                            {
                                pr.CustomerGroups.Add(cr.Id);
                                await _permissionService.UpdatePermission(pr);
                            }
                        }
                        else
                        {
                            if (pr.CustomerGroups.FirstOrDefault(x => x == cr.Id) != null)
                            {
                                pr.CustomerGroups.Remove(cr.Id);
                                await _permissionService.UpdatePermission(pr);
                            }
                        }
                    }
                }
                Success(_translationService.GetResource("Admin.Configuration.Permissions.Updated"));
            }
            else
            {
                IPermissionProvider provider = new PermissionProvider();
                await _mediator.Send(new InstallNewPermissionsCommand() { PermissionProvider = provider });

                Success(_translationService.GetResource("Admin.Configuration.Permissions.Installed"));
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> PermissionsAction(string systemName, string customeGroupId)
        {
            var model = new PermissionActionModel()
            {
                SystemName = systemName,
                CustomerGroupId = customeGroupId,
            };

            var customerGroup = await _groupService.GetCustomerGroupById(customeGroupId);
            if (customerGroup != null)
            {
                model.CustomerGroupName = customerGroup.Name;
            }
            else
            {
                ViewBag.ClosePage = true;
                return await PermissionsAction(systemName, customeGroupId);
            }

            var permissionRecord = await _permissionService.GetPermissionBySystemName(systemName);
            if (permissionRecord != null)
            {
                model.AvailableActions = permissionRecord.Actions.ToList();
                model.PermissionName = permissionRecord.GetTranslationPermissionName(_translationService, _workContext);
            }
            else
            {
                ViewBag.ClosePage = true;
                return await PermissionsAction(systemName, customeGroupId);
            }

            model.DeniedActions = (await _permissionService.GetPermissionActions(systemName, customeGroupId)).Select(x => x.Action).ToList();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> PermissionsAction(IFormCollection form)
        {
            var systemname = form["SystemName"].ToString();
            var customergroupId = form["CustomerGroupId"].ToString();

            var selected = form["SelectedActions"].ToList();

            //remove denied actions
            var deniedActions = await _permissionService.GetPermissionActions(systemname, customergroupId);
            foreach (var action in deniedActions)
            {
                await _permissionService.DeletePermissionAction(action);
            }

            //insert denied actions
            var permissionRecord = await _permissionService.GetPermissionBySystemName(systemname);
            var insertActions = permissionRecord.Actions.Except(selected);

            foreach (var item in insertActions)
            {
                await _permissionService.InsertPermissionAction(new PermissionAction()
                {
                    Action = item,
                    CustomerGroupId = customergroupId,
                    SystemName = systemname
                });
            }
            ViewBag.ClosePage = true;
            return await PermissionsAction(systemname, customergroupId);
        }
        #endregion
    }
}

src/Web/Grand.Web.Admin/Areas/Admin/Views/Permission/Index.cshtml
@model PermissionMappingModel
@{
    //page title
    ViewBag.Title = Loc["Admin.Configuration.Permissions"];
}
<form asp-area="@Constants.AreaAdmin" asp-controller="Permission" asp-action="Index" method="post">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-user-secret"></i>
                        @Loc["Admin.Configuration.Permissions"]
                    </div>
                    <div class="actions">
                        <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @Loc["Admin.Common.Save"] </button>
                        <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @Loc["Admin.Configuration.Permissions.InstallMissingPermisions"] </button>
                    </div>
                    <vc:admin-widget widget-zone="permission_list_buttons" additional-data="null" />
                </div>
                <div class="x_content form">
                    <div class="form-horizontal">
                        <div class="form-body">
                            <div class="form-group">
                                <div class="col-md-12 col-sm-12">
                                    @if (Model.AvailablePermissions.Count == 0)
                                    {
                                        <text>No permissions defined</text>
                                    }
                                    else if (Model.AvailableCustomerGroups.Count == 0)
                                    {
                                        <text>No customer groups available</text>
                                    }
                                    else
                                    {
                                    <script>
                                            function checkCategory(checkbox) {
                                                var cbox = checkbox;
                                                var input = $(checkbox).closest("td").find("ul input");
                                                $(input).each(function () {
                                                    $(this).prop('checked', $(cbox).is(':checked')).change();
                                                });
                                            }
                                            $(document).ready(function () {
                                                @foreach (var cr in Model.AvailableCustomerGroups)
                                                {
                                                    <text>
                                                        $('#selectall-@(cr.Id)').click(function () {
                                                            $('.allow_@(cr.Id)').prop('checked', $(this).is(':checked')).change();
                                                        });
                                                    </text>
                                                }
                                            });
                                    </script>
                                        <div class="permissions-table-container">
                                            <div class="table-responsive">
                                                <table class="table table-bordered tableFixHead permissions-table">
                                                    <thead>
                                                        <tr>
                                                            <th class="first-th" scope="col">
                                                                <div class="d-flex justify-content-center align-items-center">
                                                                    <strong>@Loc["Admin.Configuration.Permissions.Permission"]</strong>
                                                                </div>
                                                            </th>
                                                            @foreach (var cr in Model.AvailableCustomerGroups)
                                                            {
                                                                <th scope="col">
                                                                    <div class="d-flex flex-column align-items-center justify-content-center">
                                                                        <strong>@cr.Name</strong>
                                                                        <label class='mt-checkbox mt-checkbox-outline control control-checkbox no-action'><input type="checkbox" id="selectall-@(cr.Id)" /> <div class="control__indicator"></div></label>
                                                                    </div>
                                                                </th>
                                                            }
                                                        </tr>
                                                    </thead>
                                                    <tbody>

                                                        @{
                                                            bool altRow = true;
                                                            var group = Model.AvailablePermissions.GroupBy(x => x.Category);
                                                        }
                                                        @foreach (var pr in group)
                                                        {
                                                            altRow = !altRow;

                                                            <tr class="@(altRow ? "altrowstyle" : "rowstyle")">
                                                                <td>
                                                                    @{
                                                                        var groupList = pr.ToList();
                                                                    }
                                                                    <button type="button" class="btn btn-info title" data-toggle="collapse" data-target=".multi-collapse-@groupList[0].Category" aria-expanded="true" aria-controls="@groupList[0].Category-collapseMain">@groupList[0].Category <i class="fa fa-chevron-down" aria-hidden="true"></i></button>
                                                                    <ul id="@groupList[0].Category-collapseMain" class="collapse show multi-collapse-@groupList[0].Category">
                                                                        @foreach (var item in groupList)
                                                                        {
                                                                            <li>
                                                                                <span>@item.Name</span>
                                                                            </li>
                                                                        }
                                                                    </ul>
                                                                </td>
                                                                @foreach (var cr in Model.AvailableCustomerGroups)
                                                                {
                                                                    <td class="checkbox-container">
                                                                        <div class="title">
                                                                            <span>@cr.Name</span>
                                                                            <label class='mt-checkbox mt-checkbox-outline control control-checkbox no-action'><input type="checkbox" onclick="checkCategory(this)" /> <div class="control__indicator"></div></label>
                                                                        </div>
                                                                        <ul class="collapse show multi-collapse-@groupList[0].Category">
                                                                            @foreach (var item in groupList)
                                                                            {
                                                                                var allowed = Model.Allowed.ContainsKey(item.SystemName) && Model.Allowed[item.SystemName][cr.Id];
                                                                                <li>
                                                                                    <label class='mt-checkbox mt-checkbox-outline control control-checkbox @if (!item.Actions) { <text>no-action</text> }'><input class="allow_@(cr.Id)" type="checkbox" value="@(item.SystemName)" name="allow_@(cr.Id)" @(allowed ? " checked=checked" : null) /> <div class="control__indicator"></div></label>
                                                                                    @if (item.Actions)
                                                                                    {
                                                                                        <a class='k-link'
                                                                                           onclick="javascript:OpenWindow('@Url.Action("PermissionsAction", "Permission", new { area = Constants.AreaAdmin })/?systemname=@(item.SystemName)&customeGroupId=@cr.Id', 600, 400, true); return false;"><i class="icon-settings"></i></a>
                                                                                    }
                                                                                </li>
                                                                            }
                                                                        </ul>
                                                                    </td>
                                                                }
                                                            </tr>
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

src/Web/Grand.Web.Admin/Areas/Admin/Views/Permission/PermissionsAction.cshtml
@model PermissionActionModel
@{
    Layout = Grand.Web.Admin.Extensions.Constants.Layout_AdminPopup;
    //page title
    ViewBag.Title = Loc["Admin.Configuration.Permissions"];
}
@if (ViewBag.ClosePage == true)
{
    <script>
        window.close();
    </script>
}
<form asp-area="@Constants.AreaAdmin" asp-controller="Permission" asp-action="PermissionsAction" method="post">
    <input asp-for="SystemName" type="hidden" />
    <input asp-for="CustomerGroupId" type="hidden" />
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-user-secret"></i>
                        @Loc["Admin.Configuration.Permissions.Actions"] (@Model.PermissionName - @Model.CustomerGroupName)
                    </div>

                </div>
                <div class="x_content form">
                    <div class="actions">
                        <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @Loc["Admin.Common.Save"] </button>
                    </div>
                    <div class="form-horizontal">
                        <div class="form-body">
                            <div class="form-group">
                                <div class="col-md-12 col-sm-12">
                                    <div class="mt-checkbox-list">
                                        @foreach (var action in Model.AvailableActions)
                                        {
                                            <label class="mt-checkbox mt-checkbox-outline control control-checkbox control control-checkbox">
                                                <input type="checkbox" name="SelectedActions" value="@action" checked="@(!Model.DeniedActions.Contains(action))" />@action
                                                <div class="control__indicator"></div>
                                            </label>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>