src/Plugins/Widgets.Slider/Areas/Admin/Controllers/WidgetsSliderController.cs
using Grand.Business.Common.Extensions;
using Grand.Business.Common.Interfaces.Configuration;
using Grand.Business.Common.Interfaces.Localization;
using Grand.Business.Common.Services.Security;
using Grand.Business.Storage.Interfaces;
using Grand.Web.Common.Controllers;
using Grand.Web.Common.DataSource;
using Grand.Web.Common.Filters;
using Grand.Web.Common.Security.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Widgets.Slider.Models;
using Widgets.Slider.Services;

namespace Widgets.Slider.Areas.Admin.Controllers
{
    [AuthorizeAdmin]
    [Area("Admin")]
    [PermissionAuthorize(PermissionSystemName.Widgets)]
    public class WidgetsSliderController : BasePluginController
    {
        private readonly IPictureService _pictureService;
        private readonly ITranslationService _translationService;
        private readonly ISliderService _sliderService;
        private readonly ILanguageService _languageService;
        private readonly SliderWidgetSettings _sliderWidgetSettings;
        private readonly ISettingService _settingService;

        public WidgetsSliderController(
            IPictureService pictureService,
            ITranslationService translationService,
            ISliderService sliderService,
            ILanguageService languageService,
            ISettingService settingService,
            SliderWidgetSettings sliderWidgetSettings)
        {
            _pictureService = pictureService;
            _translationService = translationService;
            _sliderService = sliderService;
            _languageService = languageService;
            _settingService = settingService;
            _sliderWidgetSettings = sliderWidgetSettings;
        }
        public IActionResult Configure()
        {
            var model = new ConfigurationModel();
            model.DisplayOrder = _sliderWidgetSettings.DisplayOrder;
            model.CustomerGroups = _sliderWidgetSettings.LimitedToGroups?.ToArray();
            model.Stores = _sliderWidgetSettings.LimitedToStores?.ToArray();
            return View(model);
        }

        [HttpPost]
        public IActionResult Configure(ConfigurationModel model)
        {
            _sliderWidgetSettings.DisplayOrder = model.DisplayOrder;
            _sliderWidgetSettings.LimitedToGroups = model.CustomerGroups == null ? new List<string>() : model.CustomerGroups.ToList();
            _sliderWidgetSettings.LimitedToStores = model.Stores == null ? new List<string>() : model.Stores.ToList();
            _settingService.SaveSetting(_sliderWidgetSettings);
            return Json("Ok");
        }

        [HttpPost]
        public async Task<IActionResult> List(DataSourceRequest command)
        {
            var sliders = await _sliderService.GetPictureSliders();

            var items = new List<SlideListModel>();
            foreach (var x in sliders)
            {
                var model = x.ToListModel();
                var picture = await _pictureService.GetPictureById(x.PictureId);
                if (picture != null)
                {
                    model.PictureUrl = await _pictureService.GetPictureUrl(picture, 150);
                }
                items.Add(model);
            }
            var gridModel = new DataSourceResult {
                Data = items,
                Total = sliders.Count
            };
            return Json(gridModel);
        }

        public async Task<IActionResult> Create()
        {
            var model = new SlideModel();
            //locales
            await AddLocales(_languageService, model.Locales);

            return View(model);
        }
        [HttpPost, ArgumentNameFilter(KeyName = "save-continue", Argument = "continueEditing")]
        public async Task<IActionResult> Create(SlideModel model, bool continueEditing)
        {
            if (ModelState.IsValid)
            {
                var pictureSlider = model.ToEntity();
                pictureSlider.Locales = model.Locales.ToLocalizedProperty();

                await _sliderService.InsertPictureSlider(pictureSlider);

                Success(_translationService.GetResource("Widgets.Slider.Added"));
                return continueEditing ? RedirectToAction("Edit", new { id = pictureSlider.Id }) : RedirectToAction("Configure");

            }
            return View(model);
        }
        public async Task<IActionResult> Edit(string id)
        {
            var slide = await _sliderService.GetById(id);
            if (slide == null)
                return RedirectToAction("Configure");

            var model = slide.ToModel();

            //locales
            await AddLocales(_languageService, model.Locales, (locale, languageId) =>
            {
                locale.Name = slide.GetTranslation(x => x.Name, languageId, false);
                locale.Description = slide.GetTranslation(x => x.Description, languageId, false);
            });

            return View(model);
        }

        [HttpPost, ArgumentNameFilter(KeyName = "save-continue", Argument = "continueEditing")]
        public async Task<IActionResult> Edit(SlideModel model, bool continueEditing)
        {
            var pictureSlider = await _sliderService.GetById(model.Id);
            if (pictureSlider == null)
                return RedirectToAction("Configure");

            if (ModelState.IsValid)
            {
                pictureSlider = model.ToEntity();
                pictureSlider.Locales = model.Locales.ToLocalizedProperty();
                await _sliderService.UpdatePictureSlider(pictureSlider);
                Success(_translationService.GetResource("Widgets.Slider.Edited"));
                return continueEditing ? RedirectToAction("Edit", new { id = pictureSlider.Id }) : RedirectToAction("Configure");

            }
            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var pictureSlider = await _sliderService.GetById(id);
            if (pictureSlider == null)
                return Json(new DataSourceResult { Errors = "This pictureSlider not exists" });

            await _sliderService.DeleteSlider(pictureSlider);

            return new JsonResult("");
        }
    }
}

src/Plugins/Widgets.Slider/Areas/Admin/Views/WidgetsSlider/Configure.cshtml
@model ConfigurationModel
@inject AdminAreaSettings adminAreaSettings
@{
    Layout = "_ConfigurePlugin";
}
@{
    //page title
    ViewBag.Title = Loc["Widgets.Slider.Manage"];
}

<div class="row">
    <div class="col-md-12">
        <div class="x_panel light form-fit">
            <div class="x_title">
                <div class="caption">
                    <i class="fa fa-sitemap"></i>
                    @Loc["Widgets.Slider.Manage"]
                </div>
                <div class="actions btn-group btn-group-devided util-btn-margin-bottom-5">
                    <a href="@Url.Action("Create", "WidgetsSlider")" class="btn green"><i class="fa fa-plus"></i><span class="hidden-xs"> @Loc["Admin.Common.AddNew"] </span></a>
                </div>
            </div>
            <div class="x_content">
                <div id="slider-grid"></div>
            </div>
            <div class="x_content form">
                <partial name="_Settings.cshtml" model="Model"/>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#slider-grid").kendoGrid({
            dataSource: {
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("List", "WidgetsSlider"))",
                        type: "POST",
                        dataType: "json"
                    },
                    destroy: {
                        url: "@Html.Raw(Url.Action("Delete", "WidgetsSlider"))",
                        type: "POST",
                        dataType: "json",
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors",
                    model: {
                        id: "Id",
                    }
                },
                error: function(e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                pageSize: @(adminAreaSettings.DefaultGridPageSize),
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            pageable: {
                refresh: true,
                pageSizes: [@(adminAreaSettings.GridPageSizes)]
            },
            editable: {
                confirmation: true,
                mode: "inline"
            },
            scrollable: false,
            columns: [{
                    field: "PictureUrl",
                    title: "@Loc["Widgets.Slider.Fields.Picture"]",
                    template: '#if(PictureUrl) {#<a href="#=PictureUrl#" target="_blank"><img src="#=PictureUrl#" width="150" /><a/># } #',
                    width: 200
                    }, {
                    field: "Name",
                    title: "@Loc["Widgets.Slider.Fields.Title"]",
                    width: 300,
                    template: '<a class="k-link" href="Edit/#=Id#">#=Name#</a>'
                    }, {
                    field: "Link",
                    title: "@Loc["Widgets.Slider.Fields.Link"]",
                    width: 150
                    }, {
                    field: "ObjectType",
                    title: "@Loc["Widgets.Slider.Fields.ObjectType"]",
                    width: 150
                    }, {
                    field: "DisplayOrder",
                    title: "@Loc["Widgets.Slider.Fields.DisplayOrder"]",
                    attributes: { style: "text-align:center" },
                    width: 100
                    }, {
                    field: "Published",
                    title: "@Loc["Widgets.Slider.Fields.Published"]",
                    width: 100,
                    minScreenWidth: 500,
                    headerAttributes: { style: "text-align:center" },
                    attributes: { style: "text-align:center" },
                    template: '# if(Published) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
                    }, 
                    {
                    command: [
                    {
                        name: "destroy",
                        text: "@Loc["Admin.Common.Delete"]"
                            }
                        ],
                        width: 200
                    }
            ]});
    });
</script>

src/Plugins/Widgets.Slider/Areas/Admin/Views/WidgetsSlider/Create.cshtml
@using Widgets.Slider.Models
@model SlideModel
@{
    //page title
    ViewBag.Title = Loc["Widgets.Slider.AddNew"];
    Layout = "_ConfigurePlugin";
}
<form asp-controller="WidgetsSlider" asp-action="Create" method="post" id="slider-form">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-sitemap"></i>
                        @Loc["Widgets.Slider.AddNew"]
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(Loc["Widgets.Slider.BackToList"], "Configure")</small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided util-btn-margin-bottom-5">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @Loc["Admin.Common.Save"] </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @Loc["Admin.Common.SaveContinue"] </button>
                        </div>
                    </div>
                </div>
                <div class="x_content form">
                    <partial name="_CreateOrUpdate.cshtml" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>

src/Plugins/Widgets.Slider/Areas/Admin/Views/WidgetsSlider/Edit.cshtml
@using Widgets.Slider.Models
@model SlideModel
@{
    //page title
    ViewBag.Title = Loc["Widgets.Slider.Edit"];
    Layout = "_ConfigurePlugin";
}
<form asp-controller="WidgetsSlider" asp-action="Edit" method="post" id="slider-form">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-sitemap"></i>
                        @Loc["Widgets.Slider.Edit"]
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(Loc["Widgets.Slider.BackToList"], "Configure")</small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided util-btn-margin-bottom-5">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @Loc["Admin.Common.Save"] </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @Loc["Admin.Common.SaveContinue"] </button>
                        </div>
                    </div>
                </div>
                <div class="x_content form">
                    <partial name="_CreateOrUpdate.cshtml" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>

src/Plugins/Widgets.Slider/Areas/Admin/Views/WidgetsSlider/_CreateOrUpdate.TabInfo.cshtml
@model SlideModel
<script>
        $(document).ready(function () {
            $("#@Html.IdFor(model => model.SliderTypeId)").change(toggleSliderType);
            toggleSliderType();
        });
        function toggleSliderType() {
            var sliderTypeId = $("#@Html.IdFor(model => model.SliderTypeId)").val();
            if (sliderTypeId == @(((int)SliderType.HomePage).ToString())) {
                $('#pnlCategory').hide();
                $('#pnlCollection').hide();
                $('#pnlBrand').hide();
            } else if (sliderTypeId == @(((int)SliderType.Category).ToString())) {
                $('#pnlCategory').show();
                $('#pnlCollection').hide();
                $('#pnlBrand').hide();
            }else if (sliderTypeId == @(((int)SliderType.Collection).ToString())) {
                $('#pnlCategory').hide();
                $('#pnlCollection').show();
                $('#pnlBrand').hide();
            }
            else if (sliderTypeId == @(((int)SliderType.Brand).ToString())) {
                $('#pnlCategory').hide();
                $('#pnlCollection').hide();
                $('#pnlBrand').show();
            }
        }
</script>
@{Func<int, HelperResult> template = @<div class="form-horizontal">
        <div class="form-body">
            <div class="form-group">
                <admin-label asp-for="@Model.Locales[item].Name" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="@Model.Locales[item].Name" />
                    <span asp-validation-for="@Model.Locales[item].Name"></span>
                </div>
            </div>
            <div class="form-group">
                <admin-label asp-for="@Model.Locales[item].Description" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="@Model.Locales[item].Description" asp-template="Editor" />
                    <span asp-validation-for="@Model.Locales[item].Description"></span>
                </div>
            </div>
            <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
        </div>
    </div>;
}
<div class="form-horizontal">
    <localized-editor localized-template=@template name="slide-info-localized" language-ids=@Model.Locales.Select(c=>c.LanguageId).ToList()>
        <div class="form-body">
            <div class="form-group">
                <admin-label asp-for="Name" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="Name" />
                    <span asp-validation-for="Name"></span>
                </div>
            </div>
            <div class="form-group">
                <admin-label asp-for="Description" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="Description" asp-template="Editor" />
                    <span asp-validation-for="Description"></span>
                </div>
            </div>
        </div>
    </localized-editor>
    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="PictureId" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="PictureId" />
                <span asp-validation-for="PictureId"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="Link" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="Link" />
                <span asp-validation-for="Link"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="Published" />
            <div class="col-md-9 col-sm-9">
                <label class="mt-checkbox mt-checkbox-outline control control-checkbox">
                    <admin-input asp-for="Published" />
                    <div class="control__indicator"></div>
                </label>
                <span asp-validation-for="Published"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="Stores" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="Stores" />
                <span asp-validation-for="Stores"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="FullWidth" />
            <div class="col-md-9 col-sm-9">
                <label class="mt-checkbox mt-checkbox-outline control control-checkbox">
                    <admin-input asp-for="FullWidth" />
                    <div class="control__indicator"></div>
                </label>
                <span asp-validation-for="FullWidth"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="SliderTypeId" />
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="SliderTypeId" asp-items="((SliderType)Model.SliderTypeId).ToSelectList()" />
                <span asp-validation-for="SliderTypeId"></span>
            </div>
        </div>
        <div class="form-group" id="pnlCategory">
            <admin-label asp-for="CategoryId" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="CategoryId" />
                <span asp-validation-for="CategoryId"></span>
            </div>
        </div>
        <div class="form-group" id="pnlCollection">
            <admin-label asp-for="CollectionId" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="CollectionId" />
                <span asp-validation-for="CollectionId"></span>
            </div>
        </div>
        <div class="form-group" id="pnlBrand">
            <admin-label asp-for="BrandId" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="BrandId" />
                <span asp-validation-for="BrandId"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="DisplayOrder" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="DisplayOrder" />
                <span asp-validation-for="DisplayOrder"></span>
            </div>
        </div>
    </div>
</div>

src/Plugins/Widgets.Slider/Areas/Admin/Views/WidgetsSlider/_CreateOrUpdate.cshtml
@model SlideModel
<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />
<admin-tabstrip name="slide-edit">
    <items>
        <tabstrip-item text="@Loc["Widgets.Slider.Info"]" tab-index="0">
            <content>
                <div>
                    <partial name="_CreateOrUpdate.TabInfo.cshtml" model="Model" />
                </div>
            </content>
        </tabstrip-item>        
    </items>
</admin-tabstrip>

src/Plugins/Widgets.Slider/Areas/Admin/Views/WidgetsSlider/_Settings.cshtml
@model ConfigurationModel

@inject Widgets.Slider.SliderWidgetSettings setting

<form method="post" id="widget-settings-form">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-body">
                    <div class="form-group">
                        <div class="col-md-3 col-sm-3 text-right">
                            <admin-label asp-for="DisplayOrder" class="control-label" />
                        </div>
                        <div class="col-md-9 col-sm-9">
                            <admin-input asp-for="DisplayOrder" />
                        </div>
                    </div>
                    <div class="form-group">
                        <admin-label asp-for="CustomerGroups" />
                        <div class="col-md-9 col-sm-9">
                            <admin-input asp-for="CustomerGroups" />
                            <span asp-validation-for="CustomerGroups"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <admin-label asp-for="Stores" />
                        <div class="col-md-9 col-sm-9">
                            <admin-input asp-for="Stores" />
                            <span asp-validation-for="Stores"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="button" id="savegeneralsettings" class="btn default" value="@Loc["Admin.Common.Save"]" />
                        <script>
                    $(function () {
                        $('#savegeneralsettings').click(function () {

                            var postData = $(this.form).serialize();
                            addAntiForgeryToken(postData);

                            $.ajax({
                                cache: false,
                                type: 'POST',
                                url: '@Url.Action("Configure", "WidgetsSlider")',
                                data: postData,
                                dataType: 'json',
                                success: function (data) {
                                    alert('Saved');
                                },
                                error: function (xhr, ajaxOptions, thrownError) {
                                    alert('Failed to add record.');
                                }
                            });
                            return false;
                        });
                    });
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>